# Программирование на Python, БИ

## НИУ ВШЭ, 2025-26 учебный год

# Семинар 14. Web Scraping. Data Parsing

Прежде чем перейти к обсуждению и практическому освоению такого процесса, как Data Scraping, необходимо для начала освежить в памяти основы языка разметки HTML, поскольку всё то, с чем нам предстоит дальше работать, будет иметь именно такую структуру и оформление.

## Язык HTML

HTML (HyperText Markup Language) — это язык разметки, используемый для представления веб-страниц в интернете (для тех, кто работал с текстовыми ячейками в юпитеровских ноутбуках — в них, например, тоже используется свой язык разметки, только попроще). Принимая во внимание, что HTML — это именно язык разметки, а не язык программирования (вопреки расхожему заблуждению), — получается, что любая html-страница — это, по сути, самый обычный текст, в котором просто отмечено, какие части представляют собой заголовок, абзац, какие — таблицу, картинку, ну и так далее. Кстати, правилом хорошего тона считается включать в html-код как раз таки только содержательные вещи — текст и разметку; все оформление и интерактив принято выносить в отдельные файлы.

В целом, чтобы было понятнее, как это всё работает, поясним, что обычно за страницей в интернете кроется примерно следующее. На сервере лежит несколько папок. В одной папке лежат сами html-страницы с размеченным текстом. В другой — хранятся файлы *css* (*Cascading Style Sheets*), в которых заданы параметры оформления этих страниц (цвет заголовков, фона, меню, ширина рамочек вокруг текста и картинок и прочее). В третьей папке находятся файлы с кодом на *JavaScript*, которые отвечают за всевозможный интерактив: будь то всплывающий перевод слова при наведении курсора, увеличение картинки при просмотре, подсветка формы для заполнения, если формат даты неверный, и так далее. JavaScript — тоже отдельный язык программирования, на котором пишется код, соответствующий интерактиву (кстати, несмотря на название, с Java он никак не связан).

Все эти файлы чётко связаны между собой: к каждой html-странице с разметкой присоединены с помощью ссылок css-файл с оформлением и код javascript. Таким образом собирается воедино весь сайт.

Иногда, впрочем, html-страницы создаются не по стандартам и в файле с текстом могут встретиться огромные куски, например, отвечающие за оформление. Это, к сожалению, значительно затрудняет работу с ними (с такими сайтами мы ещё столкнемся в дальнейшем).

Сегодня мы с вами начнем разбирать веб-скрейпинг и дата-парсинг для html-файлов. Обычно два этих процесса связаны, просто парсинг — более узкое понятие. Веб-скрейпинг (*web scraping*) — это в целом процесс выгрузки данных с веб-страниц; а парсинг (*parsing*) — это выбор текста из файла с разметкой, например из xml или html, как у нас.

Но прежде, чем разбирать, как осуществляется работа с html-файлами, давайте получше познакомимся с их структурой. Для этого параллельно с рассмотрением дальнейших ячеек ноутбука предлагаем зайти на сайт [w3schools.com](https://www.w3schools.com/Html/) и открыть раздел [Try it yourself](https://www.w3schools.com/Html/tryit.asp?filename=tryhtml_default). W3Schools — отличный учебный инструмент для создания html-файлов: на сайте у них в целом много документации и тьюториалов по html, css и веб-дизайну вообще. Почитайте потом на досуге, если интересно!

Но вернемся к структуре HTML-файлов. Для начала стоит упомянуть, что в HTML для разметки везде используются тэги — служебные слова в треугольных скобках `<>`. Тэги бывают двух видов: открывающие и закрывающие. Открывающие тэги выглядят так, как представлено выше, а закрывающие — почти так же, но начинаются с прямого слэша (`/`).

Вся страница заключается в тэг `<html></html>`. В начале обычно указывается какая-то мета-информация: язык страницы, кодировка, метки, название и прочее. Здесь, правда, такого нет. "Тело" документа — собственно страница, которая отображается при просмотре, — заключается в тэг `<body></body>`.

Для заголовков используются тэги с `h` (`h` — от *header*): тэги `<h1></h1>`  — для заголовков первого уровня, тэг `<h2></h2>` — для заголовков второго уровня и так далее. В тэги `<p></p>` заключаются абзацы (`p` — от *paragraph*).

Приостановимся пока с теорией и приступим к созданию своей первой html-странички! Вначале внесем изменения в файл — создадим страничку "о себе". Для этого можете скопировать код ниже и вставить его в поле в разделе *Try it Yourself*, а затем нажать кнопку *Run*.

In [ ]:
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>

<h1>Моя первая html-страница</h1>
<h2>О себе</h2>
<p>Я учусь создавать html-страницы.</p>

</body>
</html>

Теперь добавим небольшую таблицу. Знания об устройстве таблиц нам понадобятся, потому что чаще всего при парсинге приходится «выцеплять» данные как раз из таблиц на html-страницах.

Вся таблица заключается в тэги `<table></table>`. Далее таблица заполняется по строкам. Строка таблицы заключается в тэги `<tr></tr>` (от *table row*); затем идут ячейки таблицы — они тоже имеют свои тэги. Если ячейка обычная — то есть не является названием столбца или строки — она окружена тэгом `<td></td>` (от *table*). Если же является — тег будет другой: `<th></th>` (от *table header*).

Используя эти знания, давайте создадим свою таблицу на нашей странице:

In [ ]:
<table>
<tr>
<th>Дата</th>
<th>Имя</th>
<th>Возраст</th>
</tr>
<tr>
<td>Иванов</td>
<td>Иван</td>
<td>28</td>
</tr>
</table>

Можем еще добавить, например, явные границы у ячеек. Для этого вставим атрибут *border* и отрегулируем ширину.

In [ ]:
<table border="1">
<tr>
<th>Фамилия</th>
<th>Имя</th>
<th>Возраст</th>
</tr>
<tr>
<td>Иванов</td>
<td>Иван</td>
<td>28</td>
</tr>
</table>

Еще добавим заголовок и на этом пока, пожалуй, закончим.

In [ ]:
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>

<h1>Моя первая html-страница</h1>
<h2>О себе</h2>
<p>Я учусь создавать html-страницы.</p>

<table border="1">
<caption>Информация</caption>
<tr>
<th>Фамилия</th>
<th>Имя</th>
<th>Возраст</th>
</tr>
<tr>
<td>Иванов</td>
<td>Иван</td>
<td>28</td>
</tr>
</table>

</body>
</html>

Получившийся результат выглядит довольно-таки просто, но в то же время он помог нам осознать основные принципы построения HTML-страниц, а также сконструировать и написать одну несложную страницу своими руками. Понимая это, мы готовы переходить к непосредственному обсуждению скрейпинга и парсинга, которые и являются главным предметом нашего сегодняшнего семинара.

## Web Scraping

Как мы уже выяснили в предыдущем блоке, процесс веб-скрейпинга подразумевает считывание данных с некоторого веб-сайта или ресурса автоматизированным образом. Для этого процесса существует очень большое количество различных подходов, возможных сценариев действия, а также специализированных библиотек, позволяющих реализовывать все эти сценарии. Ниже мы с вами рассмотрим пример лишь одного такого алгоритма, но, разумеется, ничто вас не ограничивает от того, чтобы в будущем действовать иначе, некоторым более продвинутым образом, со своими, подобранными вами библиотеками и так далее.

Один из возможных алгоритмов скрейпинга (которого мы будем вместе придерживаться сегодня):

* указать в коде адрес интересующего сайта, откуда вы хотите скачать данные (с использованием библиотеки requests)

* сохранить веб-страницу в программе (html-код вашей страницы)

* выбрать данные, которые нужно собрать (с использованием библиотеки BeautifulSoup)

* записать данные в csv-файл

* если нужно соскрейпить несколько страниц — повторить процесс для каждой из них.

Итак, давайте приступим к реализации этого алгоритма на практике!

Начнём с довольно интересной задачи по анализу новостей с одного известного российского научно-популярного портала с довольно-таки специфическим позиционированием — называется N + 1. Если вы ничего не слышали про данный портал и не понимаете, что я имею в виду под специфическим позиционированием, — не переживайте: очень скоро вы всё сами увидите! :)

В рамках анализа, который мы потенциально собираемся осуществить на основе данных с этого ресурса, собранных как раз-таки методами веб-скрейпинга и дата-парсинга, — поставим перед собой следующие цели:

- Понять, каким образом можно автоматически выгрузить новости с сайта, и собственно проделать это на практике;
- Сохранить все актуальные новости, — а точнее, ключевую информацию об этих новостях, — в датафрейм pandas;
- Осуществить выгрузку собранных данных из программы в csv-файл; скачать, сохранить файл; получить посредством этого возможность использовать результаты проделанных действий в дальнейшем в наших исследованиях и анализе.

Приступим к реализации нашей амбициозной задачи и для начала, пожалуй, заглянем на сам [портал](https://nplus1.ru/).

### Выгрузка данных через requests

Окей, мы посмотрели на титульную страницу портала, примерно поняли, с чем мы работаем, и можем теперь перейти непосредственно к скрейпингу.

Сначала выгрузим весь html-код страницы и сохраним его в отдельную переменную. Для этого нам потребуется библиотека `requests`. Документация библиотеки: https://requests.readthedocs.io/en/latest/

Импортируем её:

In [ ]:
import requests

Сохраним ссылку на главную страницу сайта в переменную `url` для удобства и выгрузим страницу. (Разумеется, это будет работать только при подключении к интернету. Если соединение будет отключено, Python выдаст `NewConnectionError`).

In [ ]:
url = 'https://nplus1.ru/' # сохраняем
page = requests.get(url) # загружаем страницу по ссылке

Если просто посмотреть на объект, ничего содержательного мы не увидим:

In [ ]:
page

Или это всё-таки содержательное?

#### Вопрос

Что такое Response 200 и какие еще "респонзы" бывают?

#### Пояснение

Без лишних слов заглянем в соответствующую [статью](https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP) на Википедии!

### Parsing с BeautifulSoup

Для продолжения работы с нашей страницей и её последующего парсинга, нам понадобится специальная библиотека: BeautifulSoup.

BeautifulSoup — это одна из самых распространенных python-библиотек для синтаксического разбора файлов HTML/XML. В веб-разработке слэнговым термином «суп из тегов» (tag soup) называют синтаксически или структурно некорректный HTML, написанный для веб-страницы. Именно отсюда и пошло такое необычное название для библиотеки. (Есть и другая, более весёлая гипотеза названия — по [ссылке](https://aliceinwonderland.fandom.com/wiki/Turtle_Soup)).

Документация BeautifulSoup: https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [ ]:
!pip install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from bs4) (4.13.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->bs4) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->bs4) (4.12.2)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2

Итак, давайте импортируем функцию `BeautifulSoup` из библиотеки `bs4` (от *beautifulsoup4*) и заберём со страницы `page` код html в виде текста.

Сохраним в переменную `soup` весь HTML-код страницы. HTML-код — это "дерево тегов", формирующее контент и всё наполнение страницы.

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
soup = BeautifulSoup(page.text, 'html')

Если выведем `soup` на экран, мы увидим то же самое, что в режиме разработчика или в режиме просмотра исходного кода (`view-source` через *Ctrl+U* в Google Chrome).

In [ ]:
soup

<!DOCTYPE html>
<html lang="ru" prefix="og: http://ogp.me/ns#">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>N + 1 — главное издание о науке, технике и технологиях</title>
<link as="font" crossorigin="" href="https://staticn1.nplus1.ru/fonts/AeonikPro/AeonikPro-Regular.woff2" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="" href="https://staticn1.nplus1.ru/fonts/Spectral/Spectral-Regular.woff" rel="preload" type="font/woff2"/>
<link href="/front-build/css/main.css?id=842e64708435127ee441c2e86afffea2" rel="stylesheet"/>
<link href="/front-build/css/app.css?id=92673ebe7185ebc42e29fc7294a4c65f" rel="stylesheet"/>
<link href="/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/site.webmanifest" rel="manifest"/>
<link color="#f26e40" href="/safari-pinned-tab.svg" rel="mask-icon"/>
<meta content="#f26e40" name="msapplication-TileColor"/>
<meta content="#ffffff" name="theme-color"/>
<link href="https://nplus1.ru" rel="canonical"/>
<meta content="8c90b02c84ac3b72" name="yandex-verification"/>
<meta content="b419949322895fc9106e24ed01be58ac" name="pmail-verification"/>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':

    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],

    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=

    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);

    })(window,document,'script','dataLayer','GTM-PJWMQBQ');</script>
<!-- End Google Tag Manager -->
<!-- HuggingCat -->
<script async="" src="https://huggingcat-web.pages.dev/mywidget.js?static=true"></script>
<script>
            (function (c, a) {
                var t = (c[a] = c[a] || []);
                t.push(["init"]);
            })(window, "hc");
        </script>
<!-- End HuggingCat -->
<!-- Ads -->
<script src="/front-build/js/modules/prebid.js?id=ddf9cebd6b4c7a66be2ec26a926d5f3c"></script>
<script src="/front-build/js/modules/initPrebidAds.js?id=1884da35da66817a1cc5dbcb173c1347"></script>
<script src="https://widget.sparrow.ru/js/embed.js"></script>
<!-- End Ads -->
<meta content="N + 1 - это научно-популярное издание, которое познакомит вас с природными явлениями, открытиями и технологиями, расскажет
 просто о сложном и поможет узнать что-то новое для себя" name="description"/>
<meta content="N + 1 — главное издание о науке, технике и технологиях" property="og:site_name"/>
<meta content="N + 1 — главное издание о науке, технике и технологиях" property="og:title"/>
<meta content="https://nplus1.ru/images-new/share_snippet.png" property="og:image"/>
<meta content="https://nplus1.ru" property="og:url"/>
<meta content="N + 1 — главное издание о науке, технике и технологиях" property="og:description"/>
<meta content="" property="og:type"/>
<script type="application/ld+json">
{
	"@context": "http://schema.org",
	"@type": "WebSite",
	"url": "https://nplus1.ru/",
	"name": "N + 1 — главное издание о науке, технике и технологиях",
	"description": "N + 1 — главное издание о науке, технике и технологиях",
	"image": "https://staticn1.nplus1.ru/image-new/share_snippet.png",
	"publisher": {
	"@type": "Organization",
		"name": "N+1",
		"logo": {
			"@type":"ImageObject",
			"url": "https://staticn1.nplus1.ru/image-new/logo-alt.png"
		},
		"sameAs": [
			"https://www.facebook.com/nplusone",
			"https://twitter.com/nplusodin",
			"https://vk.com/nplusone",
			"https://ok.ru/nplus1",
			"https://soundcloud.com/nplus_1",
			"https://t.me/nplusone"
		]
	},
	"potentialAction":{
		"@type":"SearchAction",
		"target":"https://nplus1.ru/search/{search_term_string}",
		"query-input":"required name=search_term_string"
	}
}

  </script>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="@nplusodin" name="twitter:site"/>
<meta content="N + 1 — главное издание о науке, технике и технологиях" name="twitter:title"/>
<meta content="N + 1 — главное издание о науке, технике и технологиях" name="twitter:description"/>
<meta content="https://nplus1.ru/images-new/share_snippet.png" name="twitter:image"/>
<link href="https://nplus1.ru/rss" rel="alternate" title="RSS" type="application/rss+xml"/>
</head>
<body class="antialiased">
<!-- Top.Mail.Ru counter -->
<script type="text/javascript">

var tmr = window.tmr || (window._tmr = []);

_tmr.push({id: "3377932", type: "pageView", start: (new Date()).getTime()});

(function (d, w, id) {

  if (d.getElementById(id)) return;

  var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true; ts.id = id;

  ts.src = "https://top-fwz1.mail.ru/js/code.js";

  var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};

  if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }

})(document, window, "tmr-code");

</script>
<noscript><div><img alt="Top.Mail.Ru" src="https://top-fwz1.mail.ru/counter?id=3377932;js=na" style="position:absolute;left:-9999px;"/></div></noscript>
<!-- /Top.Mail.Ru counter -->
<!-- Google Tag Manager (noscript) -->
<noscript><iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-PJWMQBQ" style="display:none;visibility:hidden" width="0"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div class="font-aeonik text-main-black flex flex-col min-h-screen pt-15 bg-light-gray" id="appfront">
<header class="bg-light-gray fixed h-15 left-0 top-0 w-full z-50" data-ref-header="" ref="headerRef">
<div class="border-b border-main-gray h-full">
<div class="2xl:max-w-1280 px-6 md:px-8 lg:px-10 xl:px-20 2xl:px-0 mx-auto flex justify-between items-center h-full" data-ref-header-container="" ref="headerContainerRef">
<button aria-label="Go" class="w-7.5 h-7.5" data-ref-header-menu-btn="" id="topMenuBtn" ref="headerMenuBtnRef">
<template v-if="isOpenDesktopMenu || isOpenMobileMenu">
<svg class="w-full h-full">
<use xlink:href="#n1_cross_menu"></use>
</svg>
</template>
<template v-else="">
<svg class="w-full h-full">
<use xlink:href="#n1_burger"></use>
</svg>
</template>
</button>
<div>
<img alt="as" height="23" loading="lazy" src="https://staticn1.nplus1.ru/image-new/logo.svg" width="57"/>
</div>
<a class="w-7.5 h-7.5" href="/search">
<svg class="w-full h-full">
<use xlink:href="#n1_pupa"></use>
</svg>
</a>
</div>
</div>
<nav :style="stylesNavDesktop" class="relative bg-light-gray max-h-0 n1_top_nav overflow-hidden" id="navMenu" v-if="isOpenDesktopMenu">
<div class="2xl:max-w-1280 px-6 md:px-8 lg:px-10 xl:px-20 2xl:px-0 mx-auto h-full flex flex-col overflow-y-auto">
<div class="py-12 mb-12 border-b border-gray-2 text-18 grid grid-cols-flow lg:grid-cols-12 gap-x-5 md:gap-x-9">
<!--
        <a @click.native="menuClose"
           class="col-span-3 flex gap-x-2 lg:gap-x-5 items-center hover:text-main transition-colors duration-75"
           href="/lk">
          <svg class="h-10 lg:h-12 w-10 lg:w-12 shrink-0">
            <use xlink:href="#n1_person"></use>
          </svg>
          <span>Личный кабинет</span>
        </a>
        -->
<a class="col-span-3 lg:col-span-2 col-start-7 lg:col-start-9 flex items-center hover:text-main transition-colors duration-75" href="https://offline.nplus1.ru/">N + offline</a>
<a class="col-span-3 lg:col-span-2 col-start-10 lg:col-start-11 flex items-center hover:text-main transition-colors duration-75" href="https://nplus.pro/">N + production</a>
</div>
<div class="grid grid-cols-12 gap-x-5 gap-y-5 md:gap-y-9 pb-6">
<div class="col-span-6 md:col-span-3 text-20 lg:text-26 xl:text-34 font-spectral flex flex-col gap-y-3">
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/about">
                О нас
              </a>
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/difficult" target="_blank">
                Сложность
              </a>
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/adv" target="_blank">
                Рекламодателям
              </a>
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/blog/2022/04/01/samotek" target="_blank">
                Авторам
              </a>
</div>
<div class="col-span-6 md:col-span-3 text-18 lg:text-24 xl:text-32 text-main flex flex-col gap-y-3">
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=946">Игры</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=869">Физика</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=874">Зоология</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=880">Астрономия</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=768">Генетика</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=890">Математика</a>
</div>
<div class="col-span-6 md:col-span-3 text-18 lg:text-24 xl:text-32 text-main flex flex-col gap-y-3">
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=871">Космонавтика</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=876">Археология</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=775">Нейронауки</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=767">На мышах</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=771">Звук</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=772">Красота</a>
</div>
<div class="col-span-6 md:col-span-3 text-18 lg:text-24 xl:text-32 text-main flex flex-col gap-y-3">
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=778">Научные закрытия</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=917">ИИ спешит на помощь</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=918">Когда рассеется дым</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=824">Книжная полка</a>
</div>
</div>
<div class="py-12 mt-auto border-t border-gray-2 text-18 grid grid-cols-12 gap-x-5 md:gap-x-9">
<ul class="flex gap-2.5">
<li>
<a class="hover:text-main" href="https://t.me/nplusone" target="_blank">
<svg class="w-12 h-12">
<use xlink:href="#n1_tg"></use>
</svg>
</a>
</li>
<li>
<a class="hover:text-main" href="https://vk.com/nplusone" target="_blank">
<svg class="w-12 h-12">
<use xlink:href="#n1_vk"></use>
</svg>
</a>
</li>
<li>
<a class="hover:text-main" href="https://ok.ru/nplus1" target="_blank">
<svg class="w-12 h-12">
<use xlink:href="#n1_ok"></use>
</svg>
</a>
</li>
<li class="w-12">
<a class="hover:text-main" href="https://twitter.com/nplusodin" target="_blank">
<svg class="w-12 h-12">
<use xlink:href="#n1_tw"></use>
</svg>
</a>
</li>
</ul>
</div>
</div>
</nav>
<nav :style="stylesNavMobile" class="relative bg-white max-h-0 n1_top_nav overflow-hidden" id="mobNavMenu" v-if="isOpenMobileMenu">
<div class="2xl:max-w-1280 px-6 md:px-8 lg:px-10 xl:px-20 2xl:px-0 mx-auto h-full flex flex-col overflow-y-auto">
<div class="text-30 font-spectral flex flex-col gap-y-5 mb-10 mt-10">
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/about">
                О нас
              </a>
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/difficult" target="_blank">
                Сложность
              </a>
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/adv" target="_blank">
                Рекламодателям
              </a>
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/blog/2022/04/01/samotek" target="_blank">
                Авторам
              </a>
</div>
<div class="text-28 text-main flex flex-col gap-y-2.5 mb-10">
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=946">Игры
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=869">Физика
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=874">Зоология
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=880">Астрономия
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=768">Генетика
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=890">Математика
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=871">Космонавтика
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=876">Археология
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=775">Нейронауки
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=767">На мышах
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=771">Звук
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=772">Красота
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=778">Научные закрытия
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=917">ИИ спешит на помощь
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=918">Когда рассеется дым
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=824">Книжная полка
          </a>
</div>
<div class="max-w-full flex py-5 border-t border-gray-2">
<div class="flex gap-x-5 overflow-x-auto">
<a class="hover:text-main whitespace-nowrap" href="https://offline.nplus1.ru/">N + offline</a>
<a class="hover:text-main whitespace-nowrap" href="https://nplus.pro/">N + production</a>
</div>
</div>
<div class="pt-5 pb-10 border-t border-gray-2 text-18">
<ul class="flex gap-2.5">
<li>
<a class="hover:text-main" href="https://t.me/nplusone" target="_blank">
<svg class="w-10 h-10">
<use xlink:href="#n1_tg"></use>
</svg>
</a>
</li>
<li>
<a class="hover:text-main" href="https://vk.com/nplusone" target="_blank">
<svg class="w-10 h-10">
<use xlink:href="#n1_vk"></use>
</svg>
</a>
</li>
<li>
<a class="hover:text-main" href="https://ok.ru/nplus1" target="_blank">
<svg class="w-10 h-10">
<use xlink:href="#n1_ok"></use>
</svg>
</a>
</li>
<li class="w-12">
<a class="hover:text-main" href="https://twitter.com/nplusodin" target="_blank">
<svg class="w-10 h-10">
<use xlink:href="#n1_tw"></use>
</svg>
</a>
</li>
</ul>
</div>
</div>
</nav>
</header>
<section class="mb-10">
<div class="2xl:max-w-1280 px-6 md:px-8 lg:px-10 xl:px-20 2xl:px-0 mx-auto mx-auto">
<div class="grid grid-cols-2 col-span-2 gap-0.5 n1_m_full n1_fs_main">
<div class="relative order-1 sm:order-1 overflow-hidden h-full sm:h-48 md:h-60 lg:h-72 xl:h-88">
<div class="absolute z-10 top-5 inset-x-4 md:inset-x-5">
<div class="flex flex-wrap gap-2 text-tags">
<a class="relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 pl-2 flex inline-flex items-center text-white text-xs sm:text-sm hover:text-main" href="https://nplus1.ru/search?tags=869">Физика
                          </a>
<a class="relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 pl-2 flex inline-flex items-center text-white text-xs sm:text-sm hover:text-main" href="https://nplus1.ru/search?tags=870">Химия
                          </a>
<a class="relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 pl-2 flex inline-flex items-center text-white text-xs sm:text-sm hover:text-main" href="https://nplus1.ru/search?tags=812">Партнерский материал
                          </a>
<a class="group inline-block relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 pl-2 flex inline-flex items-center max-w-full text-white hover:text-main" href="/material/difficulty/5">
<svg class="w-4 h-4 mr-1 stroke-current">
<use xlink:href="#n1_star"></use>
</svg>
<span class="transition-colors duration-75 overflow-hidden text-ellipsis whitespace-nowrap">5.8</span>
</a>
</div>
</div>
<a class="" href="https://nplus1.ru/material/2025/02/10/vyzov-2024-breakthroughs">
<div class="relative order-1 sm:order-1 overflow-hidden h-full sm:h-48 md:h-60 lg:h-72 xl:h-88">
<div class="hidden sm:block max-height-[333px]">
<div class="-inset-0.5 absolute group">
<picture>
<source media="(min-width: 640px)" srcset="https://minio.nplus1.ru/app-images/990836/conversions/07485bc8b66c6332ba371b13f11101fe-conversion-webp.webp">
<source media="(max-width: 639px)" srcset="https://minio.nplus1.ru/app-images/990837/conversions/a7ecdc20129482f4d706e46b9c6e3905-conversion-webp.webp">
<img alt="Свет, нейтроны и гетероциклы" class="w-full h-full object-cover brightness-75" loading="lazy" src="https://staticn1.nplus1.ru/image-new/blank.jpeg"/>
</source></source></picture>
</div>
</div>
<div class="block sm:hidden">
<div class="-inset-0.5 absolute max-height-[333px]">
<picture>
<source media="(min-width: 640px)" srcset="https://minio.nplus1.ru/app-images/990836/conversions/07485bc8b66c6332ba371b13f11101fe-conversion-webp.webp">
<source media="(max-width: 639px)" srcset="https://minio.nplus1.ru/app-images/990837/conversions/a7ecdc20129482f4d706e46b9c6e3905-conversion-webp.webp">
<img alt="Свет, нейтроны и гетероциклы" class="w-full h-full object-cover brightness-75" loading="lazy" src="https://staticn1.nplus1.ru/image-new/blank.jpeg"/>
</source></source></picture>
</div>
</div>
<div class="absolute bottom-5 inset-x-4 md:inset-x-5">
<h3 class="text-white text-14 md:text-22 xl:text-32 mb-1">Свет, нейтроны и гетероциклы</h3>
<div class="text-white max-h-[90px] overflow-hidden sm:max-h-full text-14 md:text-22 xl:text-34 font-serif font-light font-spectral">
                  За какие прорывы наградили ученых Премией «ВЫЗОВ» 2024
                </div>
</div>
</div>
</a>
</div>
<div class="relative order-1 sm:order-1 overflow-hidden h-full sm:h-48 md:h-60 lg:h-72 xl:h-88">
<div class="absolute z-10 top-5 inset-x-4 md:inset-x-5">
<div class="flex flex-wrap gap-2 text-tags">
<a class="relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 pl-2 flex inline-flex items-center text-white text-xs sm:text-sm hover:text-main" href="https://nplus1.ru/search?tags=869">Физика
                          </a>
<a class="group inline-block relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 pl-2 flex inline-flex items-center max-w-full text-white hover:text-main" href="/material/difficulty/8">
<svg class="w-4 h-4 mr-1 stroke-current">
<use xlink:href="#n1_star"></use>
</svg>
<span class="transition-colors duration-75 overflow-hidden text-ellipsis whitespace-nowrap">8.7</span>
</a>
</div>
</div>
<a class="" href="https://nplus1.ru/material/2025/02/07/quantum-correction">
<div class="relative order-1 sm:order-1 overflow-hidden h-full sm:h-48 md:h-60 lg:h-72 xl:h-88">
<div class="hidden sm:block max-height-[333px]">
<div class="-inset-0.5 absolute group">
<picture>

Для просмотра, честно говоря, выглядит не очень удобно. «Причешем» немного наш `soup` — для этого воспользуемся методом `.prettify()` в сочетании с функцией `print()`.

In [ ]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="ru" prefix="og: http://ogp.me/ns#">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
   N + 1 — главное издание о науке, технике и технологиях
  </title>
  <link as="font" crossorigin="" href="https://staticn1.nplus1.ru/fonts/AeonikPro/AeonikPro-Regular.woff2" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="https://staticn1.nplus1.ru/fonts/Spectral/Spectral-Regular.woff" rel="preload" type="font/woff2"/>
  <link href="/front-build/css/main.css?id=842e64708435127ee441c2e86afffea2" rel="stylesheet"/>
  <link href="/front-build/css/app.css?id=92673ebe7185ebc42e29fc7294a4c65f" rel="stylesheet"/>
  <link href="/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
  <link href="/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
  <link href="/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
  <link href="/site.webmanifest" rel="manifest"/>
  <link color="#f26e40" href="/safari-pinned-tab.svg" rel="mask-icon"/>
  <meta content="#f26e40" name="msapplication-TileColor"/>
  <meta content="#ffffff" name="theme-color"/>
  <link href="https://nplus1.ru" rel="canonical"/>
  <meta content="8c90b02c84ac3b72" name="yandex-verification"/>
  <meta content="b419949322895fc9106e24ed01be58ac" name="pmail-verification"/>
  <!-- Google Tag Manager -->
  <script>
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':

    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],

    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=

    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);

    })(window,document,'script','dataLayer','GTM-PJWMQBQ');
  </script>
  <!-- End Google Tag Manager -->
  <!-- HuggingCat -->
  <script async="" src="https://huggingcat-web.pages.dev/mywidget.js?static=true">
  </script>
  <script>
   (function (c, a) {
                var t = (c[a] = c[a] || []);
                t.push(["init"]);
            })(window, "hc");
  </script>
  <!-- End HuggingCat -->
  <!-- Ads -->
  <script src="/front-build/js/modules/prebid.js?id=ddf9cebd6b4c7a66be2ec26a926d5f3c">
  </script>
  <script src="/front-build/js/modules/initPrebidAds.js?id=1884da35da66817a1cc5dbcb173c1347">
  </script>
  <script src="https://widget.sparrow.ru/js/embed.js">
  </script>
  <!-- End Ads -->
  <meta content="N + 1 - это научно-популярное издание, которое познакомит вас с природными явлениями, открытиями и технологиями, расскажет
 просто о сложном и поможет узнать что-то новое для себя" name="description"/>
  <meta content="N + 1 — главное издание о науке, технике и технологиях" property="og:site_name"/>
  <meta content="N + 1 — главное издание о науке, технике и технологиях" property="og:title"/>
  <meta content="https://nplus1.ru/images-new/share_snippet.png" property="og:image"/>
  <meta content="https://nplus1.ru" property="og:url"/>
  <meta content="N + 1 — главное издание о науке, технике и технологиях" property="og:description"/>
  <meta content="" property="og:type"/>
  <script type="application/ld+json">
   {
	"@context": "http://schema.org",
	"@type": "WebSite",
	"url": "https://nplus1.ru/",
	"name": "N + 1 — главное издание о науке, технике и технологиях",
	"description": "N + 1 — главное издание о науке, технике и технологиях",
	"image": "https://staticn1.nplus1.ru/image-new/share_snippet.png",
	"publisher": {
	"@type": "Organization",
		"name": "N+1",
		"logo": {
			"@type":"ImageObject",
			"url": "https://staticn1.nplus1.ru/image-new/logo-alt.png"
		},
		"sameAs": [
			"https://www.facebook.com/nplusone",
			"https://twitter.com/nplusodin",
			"https://vk.com/nplusone",
			"https://ok.ru/nplus1",
			"https://soundcloud.com/nplus_1",
			"https://t.me/nplusone"
		]
	},
	"potentialAction":{
		"@type":"SearchAction",
		"target":"https://nplus1.ru/search/{search_term_string}",
		"query-input":"required name=search_term_string"
	}
}
  </script>
  <meta content="summary_large_image" name="twitter:card"/>
  <meta content="@nplusodin" name="twitter:site"/>
  <meta content="N + 1 — главное издание о науке, технике и технологиях" name="twitter:title"/>
  <meta content="N + 1 — главное издание о науке, технике и технологиях" name="twitter:description"/>
  <meta content="https://nplus1.ru/images-new/share_snippet.png" name="twitter:image"/>
  <link href="https://nplus1.ru/rss" rel="alternate" title="RSS" type="application/rss+xml"/>
 </head>
 <body class="antialiased">
  <!-- Top.Mail.Ru counter -->
  <script type="text/javascript">
   var tmr = window.tmr || (window._tmr = []);

_tmr.push({id: "3377932", type: "pageView", start: (new Date()).getTime()});

(function (d, w, id) {

  if (d.getElementById(id)) return;

  var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true; ts.id = id;

  ts.src = "https://top-fwz1.mail.ru/js/code.js";

  var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};

  if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }

})(document, window, "tmr-code");
  </script>
  <noscript>
   <div>
    <img alt="Top.Mail.Ru" src="https://top-fwz1.mail.ru/counter?id=3377932;js=na" style="position:absolute;left:-9999px;"/>
   </div>
  </noscript>
  <!-- /Top.Mail.Ru counter -->
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-PJWMQBQ" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <div class="font-aeonik text-main-black flex flex-col min-h-screen pt-15 bg-light-gray" id="appfront">
   <header class="bg-light-gray fixed h-15 left-0 top-0 w-full z-50" data-ref-header="" ref="headerRef">
    <div class="border-b border-main-gray h-full">
     <div class="2xl:max-w-1280 px-6 md:px-8 lg:px-10 xl:px-20 2xl:px-0 mx-auto flex justify-between items-center h-full" data-ref-header-container="" ref="headerContainerRef">
      <button aria-label="Go" class="w-7.5 h-7.5" data-ref-header-menu-btn="" id="topMenuBtn" ref="headerMenuBtnRef">
       <template v-if="isOpenDesktopMenu || isOpenMobileMenu">
        <svg class="w-full h-full">
         <use xlink:href="#n1_cross_menu">
         </use>
        </svg>
       </template>
       <template v-else="">
        <svg class="w-full h-full">
         <use xlink:href="#n1_burger">
         </use>
        </svg>
       </template>
      </button>
      <div>
       <img alt="as" height="23" loading="lazy" src="https://staticn1.nplus1.ru/image-new/logo.svg" width="57"/>
      </div>
      <a class="w-7.5 h-7.5" href="/search">
       <svg class="w-full h-full">
        <use xlink:href="#n1_pupa">
        </use>
       </svg>
      </a>
     </div>
    </div>
    <nav :style="stylesNavDesktop" class="relative bg-light-gray max-h-0 n1_top_nav overflow-hidden" id="navMenu" v-if="isOpenDesktopMenu">
     <div class="2xl:max-w-1280 px-6 md:px-8 lg:px-10 xl:px-20 2xl:px-0 mx-auto h-full flex flex-col overflow-y-auto">
      <div class="py-12 mb-12 border-b border-gray-2 text-18 grid grid-cols-flow lg:grid-cols-12 gap-x-5 md:gap-x-9">
       <!--
        <a @click.native="menuClose"
           class="col-span-3 flex gap-x-2 lg:gap-x-5 items-center hover:text-main transition-colors duration-75"
           href="/lk">
          <svg class="h-10 lg:h-12 w-10 lg:w-12 shrink-0">
            <use xlink:href="#n1_person"></use>
          </svg>
          <span>Личный кабинет</span>
        </a>
        -->
       <a class="col-span-3 lg:col-span-2 col-start-7 lg:col-start-9 flex items-center hover:text-main transition-colors duration-75" href="https://offline.nplus1.ru/">
        N + offline
       </a>
       <a class="col-span-3 lg:col-span-2 col-start-10 lg:col-start-11 flex items-center hover:text-main transition-colors duration-75" href="https://nplus.pro/">
        N + production
       </a>
      </div>
      <div class="grid grid-cols-12 gap-x-5 gap-y-5 md:gap-y-9 pb-6">
       <div class="col-span-6 md:col-span-3 text-20 lg:text-26 xl:text-34 font-spectral flex flex-col gap-y-3">
        <a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/about">
         О нас
        </a>
        <a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/difficult" target="_blank">
         Сложность
        </a>
        <a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/adv" target="_blank">
         Рекламодателям
        </a>
        <a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/blog/2022/04/01/samotek" target="_blank">
         Авторам
        </a>
       </div>
       <div class="col-span-6 md:col-span-3 text-18 lg:text-24 xl:text-32 text-main flex flex-col gap-y-3">
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=946">
         Игры
        </a>
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=869">
         Физика
        </a>
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=874">
         Зоология
        </a>
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=880">
         Астрономия
        </a>
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=768">
         Генетика
        </a>
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=890">
         Математика
        </a>
       </div>
       <div class="col-span-6 md:col-span-3 text-18 lg:text-24 xl:text-32 text-main flex flex-col gap-y-3">
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=871">
         Космонавтика
        </a>
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=876">
         Археология
        </a>
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=775">
         Нейронауки
        </a>
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=767">
         На мышах
        </a>
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=771">
         Звук
        </a>
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=772">
         Красота
        </a>
       </div>
       <div class="col-span-6 md:col-span-3 text-18 lg:text-24 xl:text-32 text-main flex flex-col gap-y-3">
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=778">
         Научные закрытия
        </a>
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=917">
         ИИ спешит на помощь
        </a>
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=918">
         Когда рассеется дым
        </a>
        <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=824">
         Книжная полка
        </a>
       </div>
      </div>
      <div class="py-12 mt-auto border-t border-gray-2 text-18 grid grid-cols-12 gap-x-5 md:gap-x-9">
       <ul class="flex gap-2.5">
        <li>
         <a class="hover:text-main" href="https://t.me/nplusone" target="_blank">
          <svg class="w-12 h-12">
           <use xlink:href="#n1_tg">
           </use>
          </svg>
         </a>
        </li>
        <li>
         <a class="hover:text-main" href="https://vk.com/nplusone" target="_blank">
          <svg class="w-12 h-12">
           <use xlink:href="#n1_vk">
           </use>
          </svg>
         </a>
        </li>
        <li>
         <a class="hover:text-main" href="https://ok.ru/nplus1" target="_blank">
          <svg class="w-12 h-12">
           <use xlink:href="#n1_ok">
           </use>
          </svg>
         </a>
        </li>
        <li class="w-12">
         <a class="hover:text-main" href="https://twitter.com/nplusodin" target="_blank">
          <svg class="w-12 h-12">
           <use xlink:href="#n1_tw">
           </use>
          </svg>
         </a>
        </li>
       </ul>
      </div>
     </div>
    </nav>
    <nav :style="stylesNavMobile" class="relative bg-white max-h-0 n1_top_nav overflow-hidden" id="mobNavMenu" v-if="isOpenMobileMenu">
     <div class="2xl:max-w-1280 px-6 md:px-8 lg:px-10 xl:px-20 2xl:px-0 mx-auto h-full flex flex-col overflow-y-auto">
      <div class="text-30 font-spectral flex flex-col gap-y-5 mb-10 mt-10">
       <a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/about">
        О нас
       </a>
       <a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/difficult" target="_blank">
        Сложность
       </a>
       <a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/adv" target="_blank">
        Рекламодателям
       </a>
       <a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/blog/2022/04/01/samotek" target="_blank">
        Авторам
       </a>
      </div>
      <div class="text-28 text-main flex flex-col gap-y-2.5 mb-10">
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=946">
        Игры
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=869">
        Физика
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=874">
        Зоология
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=880">
        Астрономия
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=768">
        Генетика
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=890">
        Математика
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=871">
        Космонавтика
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=876">
        Археология
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=775">
        Нейронауки
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=767">
        На мышах
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=771">
        Звук
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=772">
        Красота
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=778">
        Научные закрытия
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=917">
        ИИ спешит на помощь
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=918">
        Когда рассеется дым
       </a>
       <a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=824">
        Книжная полка
       </a>
      </div>
      <div class="max-w-full flex py-5 border-t border-gray-2">
       <div class="flex gap-x-5 overflow-x-auto">
        <a class="hover:text-main whitespace-nowrap" href="https://offline.nplus1.ru/">
         N + offline
        </a>
        <a class="hover:text-main whitespace-nowrap" href="https://nplus.pro/">
         N + production
        </a>
       </div>
      </div>
      <div class="pt-5 pb-10 border-t border-gray-2 text-18">
       <ul class="flex gap-2.5">
        <li>
         <a class="hover:text-main" href="https://t.me/nplusone" target="_blank">
          <svg class="w-10 h-10">
           <use xlink:href="#n1_tg">
           </use>
          </svg>
         </a>
        </li>
        <li>
         <a class="hover:text-main" href="https://vk.com/nplusone" target="_blank">
          <svg class="w-10 h-10">
           <use xlink:href="#n1_vk">
           </use>
          </svg>
         </a>
        </li>
        <li>
         <a class="hover:text-main" href="https://ok.ru/nplus1" target="_blank">
          <svg class="w-10 h-10">
           <use xlink:href="#n1_ok">
           </use>
          </svg>
         </a>
        </li>
        <li class="w-12">
         <a class="hover:text-main" href="https://twitter.com/nplusodin" target="_blank">
          <svg class="w-10 h-10">
           <use xlink:href="#n1_tw">
           </use>
          </svg>
         </a>
        </li>
       </ul>
      </div>
     </div>
    </nav>
   </header>
   <section class="mb-10">
    <div class="2xl:max-w-1280 px-6 md:px-8 lg:px-10 xl:px-20 2xl:px-0 mx-auto mx-auto">
     <div class="grid grid-cols-2 col-span-2 gap-0.5 n1_m_full n1_fs_main">
      <div class="relative order-1 sm:order-1 overflow-hidden h-full sm:h-48 md:h-60 lg:h-72 xl:h-88">
       <div class="absolute z-10 top-5 inset-x-4 md:inset-x-5">
        <div class="flex flex-wrap gap-2 text-tags">
         <a class="relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 pl-2 flex inline-flex items-center text-white text-xs sm:text-sm hover:text-main" href="https://nplus1.ru/search?tags=869">
          Физика
         </a>
         <a class="relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 pl-2 flex inline-flex items-center text-white text-xs sm:text-sm hover:text-main" href="https://nplus1.ru/search?tags=870">
          Химия
         </a>
         <a class="relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 pl-2 flex inline-flex items-center text-white text-xs sm:text-sm hover:text-main" href="https://nplus1.ru/search?tags=812">
          Партнерский материал
         </a>
         <a class="group inline-block relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 pl-2 flex inline-flex items-center max-w-full text-white hover:text-main" href="/material/difficulty/5">
          <svg class="w-4 h-4 mr-1 stroke-current">
           <use xlink:href="#n1_star">
           </use>
          </svg>
          <span class="transition-colors duration-75 overflow-hidden text-ellipsis whitespace-nowrap">
           5.8
          </span>
         </a>
        </div>
       </div>
       <a class="" href="https://nplus1.ru/material/2025/02/10/vyzov-2024-breakthroughs">
        <div class="relative order-1 sm:order-1 overflow-hidden h-full sm:h-48 md:h-60 lg:h-72 xl:h-88">
         <div class="hidden sm:block max-height-[333px]">
          <div class="-inset-0.5 absolute group">
           <picture>
            <source media="(min-width: 640px)" srcset="https://minio.nplus1.ru/app-images/990836/conversions/07485bc8b66c6332ba371b13f11101fe-conversion-webp.webp">
             <source media="(max-width: 639px)" srcset="https://minio.nplus1.ru/app-images/990837/conversions/a7ecdc20129482f4d706e46b9c6e3905-conversion-webp.webp">
              <img alt="Свет, нейтроны и гетероциклы" class="w-full h-full object-cover brightness-75" loading="lazy" src="https://staticn1.nplus1.ru/image-new/blank.jpeg"/>
             </source>
            </source>
           </picture>
          </div>
         </div>
         <div class="block sm:hidden">

В такой выдаче ориентироваться чуть-чуть удобнее (но при желании, то же самое можно увидеть в браузере, на большом экране).

#### Вопрос

Хорошо, мы научились считывать данные с сайта и продемонстрировали это на практике для нашего веб-ресурса. Но... что же нам делать дальше? Как на основе этого сырого html-кода получить доступ к новостям на портале?

Есть идеи?

#### Пояснение

Для того чтобы это сделать, давайте с главной страницы сайта соберем все ссылки, из которых потом выделим ссылки на страницы с новостями. Ссылки в html-файле всегда заключены в тэг `<a></a>` и имеют атрибут `href`.

Помочь нам в поиске ссылок может функция **`soup.find('a')`**, которая найдет первый в дереве тег `<a>`.

Если нам нужно найти не только первый элемент, а все элементы по определенному признаку, следует использовать функцию **`soup.find_all('a')`**

In [ ]:
for link in soup.find_all('a'):
    print(link.get('href'))

/search
https://offline.nplus1.ru/
https://nplus.pro/
https://nplus1.ru/about
https://nplus1.ru/difficult
https://nplus1.ru/adv
https://nplus1.ru/blog/2022/04/01/samotek
https://nplus1.ru/search?tags=946
https://nplus1.ru/search?tags=869
https://nplus1.ru/search?tags=874
https://nplus1.ru/search?tags=880
https://nplus1.ru/search?tags=768
https://nplus1.ru/search?tags=890
https://nplus1.ru/search?tags=871
https://nplus1.ru/search?tags=876
https://nplus1.ru/search?tags=775
https://nplus1.ru/search?tags=767
https://nplus1.ru/search?tags=771
https://nplus1.ru/search?tags=772
https://nplus1.ru/search?tags=778
https://nplus1.ru/search?tags=917
https://nplus1.ru/search?tags=918
https://nplus1.ru/search?tags=824
https://t.me/nplusone
https://vk.com/nplusone
https://ok.ru/nplus1
https://twitter.com/nplusodin
https://nplus1.ru/about
https://nplus1.ru/difficult
https://nplus1.ru/adv
https://nplus1.ru/blog/2022/04/01/samotek
https://nplus1.ru/search?tags=946
https://nplus1.ru/search?tags=869
https://nplus1.ru/search?tags=874
https://nplus1.ru/search?tags=880
https://nplus1.ru/search?tags=768
https://nplus1.ru/search?tags=890
https://nplus1.ru/search?tags=871
https://nplus1.ru/search?tags=876
https://nplus1.ru/search?tags=775
https://nplus1.ru/search?tags=767
https://nplus1.ru/search?tags=771
https://nplus1.ru/search?tags=772
https://nplus1.ru/search?tags=778
https://nplus1.ru/search?tags=917
https://nplus1.ru/search?tags=918
https://nplus1.ru/search?tags=824
https://offline.nplus1.ru/
https://nplus.pro/
https://t.me/nplusone
https://vk.com/nplusone
https://ok.ru/nplus1
https://twitter.com/nplusodin
https://nplus1.ru/search?tags=869
https://nplus1.ru/search?tags=870
https://nplus1.ru/search?tags=812
/material/difficulty/5
https://nplus1.ru/material/2025/02/10/vyzov-2024-breakthroughs
https://nplus1.ru/search?tags=869
/material/difficulty/8
https://nplus1.ru/material/2025/02/07/quantum-correction
https://nplus1.ru/search?tags=908
/material/difficulty/2
https://nplus1.ru/blog/2025/02/06/perst-51
https://nplus1.ru/search?tags=874
/material/difficulty/2
https://nplus1.ru/news/2025/02/07/bonobos-theory-of-mind
/news/2025/02/10
https://nplus1.ru/search?tags=884
/material/difficulty/5
https://nplus1.ru/news/2025/02/10/tibetan-plateau-tectonic-evolution
/news/2025/02/10
https://nplus1.ru/search?tags=884
/material/difficulty/6
https://nplus1.ru/news/2025/02/10/inner-core-boundary-deformation
/news/2025/02/10
https://nplus1.ru/search?tags=882
/material/difficulty/2
https://nplus1.ru/news/2025/02/10/real-world-math
/news/2025/02/10
https://nplus1.ru/search?tags=877
/material/difficulty/3
https://nplus1.ru/news/2025/02/10/byzantine-ascetic-burial
/news/2025/02/10
https://nplus1.ru/search?tags=884
/material/difficulty/1
https://nplus1.ru/news/2025/02/10/cayman-islands-earthquake
/news/2025/02/10
https://nplus1.ru/search?tags=876
/material/difficulty/3
https://nplus1.ru/news/2025/02/10/valdegoba-cave
/news/2025/02/10
https://nplus1.ru/search?tags=869
/material/difficulty/5
https://nplus1.ru/news/2025/02/10/elastocaloric-cooling
/news/2025/02/10
https://nplus1.ru/search?tags=871
/material/difficulty/1
https://nplus1.ru/news/2025/02/10/super-heavy-b15-static-fire-test
/news/2025/02/07
https://nplus1.ru/search?tags=874
/material/difficulty/2
https://nplus1.ru/news/2025/02/07/bonobos-theory-of-mind
/news/2025/02/07
https://nplus1.ru/search?tags=877
/material/difficulty/3
https://nplus1.ru/news/2025/02/07/magdalenian-cannibalism
/news/2025/02/07
https://nplus1.ru/search?tags=873
/material/difficulty/3
https://nplus1.ru/news/2025/02/07/taste-the-tess
/news/2025/02/07
https://nplus1.ru/search?tags=882
/material/difficulty/1
https://nplus1.ru/news/2025/02/07/so-sad-but-true
https://nplus1.ru/blog/2025/02/07/shamans
/blog/2025/02/07
https://nplus1.ru/search?tags=877
/material/difficulty/1
https://nplus1.ru/blog/2025/02/07/shamans
https://nplus1.ru/blog/2025/02/05/russias-turkish-wars
/blog/2025/02/05
https://nplus1.ru/search?tags=817
/material/difficulty/1
https://nplus1.ru/blog/2025/02/05/russias-turkish-wars
/news/2025/02/07
https://nplus1.ru/search?tags=878
/material/difficulty/4
https://nplus1.ru/news/2025/02/07/vegavis-iaai-skull
/news/2025/02/07
https://nplus1.ru/search?tags=872
/material/difficulty/1
https://nplus1.ru/news/2025/02/07/temporal-turnover
https://nplus1.ru/material/2025/01/03/choose-your-bigfoot
/material/2025/01/03
https://nplus1.ru/search?tags=877
/material/difficulty/3
https://nplus1.ru/material/2025/01/03/choose-your-bigfoot
https://nplus1.ru/material/2025/01/02/dendrochristmas
https://nplus1.ru/search?tags=872
/material/difficulty/4
https://nplus1.ru/material/2025/01/02/dendrochristmas
/blog/2025/02/10
https://nplus1.ru/search?tags=890
/material/difficulty/1
/author/mann-ivanov-i-ferber
https://nplus1.ru/blog/2025/02/10/fantastic-numbers
/news/2025/02/06
https://nplus1.ru/search?tags=869
/material/difficulty/1
https://nplus1.ru/news/2025/02/06/cracking-boiled-egg
/news/2025/02/06
https://nplus1.ru/search?tags=870
/material/difficulty/7
https://nplus1.ru/news/2025/02/06/mo-as-good-as-ir
/news/2025/02/06
https://nplus1.ru/search?tags=877
/material/difficulty/4
https://nplus1.ru/news/2025/02/06/genomic-history-of-north-pontic-region
https://nplus1.ru/material/2024/12/31/wild-santa
/material/2024/12/31
https://nplus1.ru/search?tags=874
/material/difficulty/3
https://nplus1.ru/material/2024/12/31/wild-santa
/news/2025/02/06
https://nplus1.ru/search?tags=873
/material/difficulty/1
https://nplus1.ru/news/2025/02/06/pig-kidneys-trial-go
/news/2025/02/06
https://nplus1.ru/search?tags=874
/material/difficulty/3
https://nplus1.ru/news/2025/02/06/rats-global-warming
https://nplus1.ru/material/2024/12/28/dopamine-in-health
/material/2024/12/28
https://nplus1.ru/search?tags=812
/material/difficulty/4
https://nplus1.ru/material/2024/12/28/dopamine-in-health
https://nplus1.ru/material/2024/12/27/migraine
https://nplus1.ru/search?tags=812
/material/difficulty/1
https://nplus1.ru/material/2024/12/27/migraine
/blog/2025/02/03
https://nplus1.ru/search?tags=894
/material/difficulty/1
/author/nlo
https://nplus1.ru/blog/2025/02/03/violence
/news/2025/02/06
https://nplus1.ru/search?tags=873
/material/difficulty/2
https://nplus1.ru/news/2025/02/06/omicron-escapes
/news/2025/02/06
https://nplus1.ru/search?tags=877
/material/difficulty/5
https://nplus1.ru/news/2025/02/06/genetic-origin-of-the-yamnaya-people
/news/2025/02/05
https://nplus1.ru/search?tags=869
/material/difficulty/3
https://nplus1.ru/news/2025/02/05/human-crowd-oscillations
https://nplus1.ru/material/2024/12/27/light-pollution
/material/2024/12/27
https://nplus1.ru/search?tags=812
/material/difficulty/2
https://nplus1.ru/material/2024/12/27/light-pollution
/news/2025/02/05
https://nplus1.ru/search?tags=872
/material/difficulty/1
https://nplus1.ru/news/2025/02/05/greenland-crevasse-fields
/news/2025/02/05
https://nplus1.ru/search?tags=873
/material/difficulty/1
https://nplus1.ru/news/2025/02/05/mobile-not-carcinogenic
https://nplus1.ru/material/2024/12/20/science-2024
/material/2024/12/20
https://nplus1.ru/search?tags=903
/material/difficulty/1
https://nplus1.ru/material/2024/12/20/science-2024
https://nplus1.ru/material/2024/12/18/practical-ml
https://nplus1.ru/search?tags=899
/material/difficulty/2
https://nplus1.ru/material/2024/12/18/practical-ml
/blog/2025/01/30
https://nplus1.ru/search?tags=908
/material/difficulty/2
/author/perst
https://nplus1.ru/blog/2025/01/30/perst-50
/news/2025/02/05
https://nplus1.ru/search?tags=885
/material/difficulty/2
https://nplus1.ru/news/2025/02/05/auricular-muscles
/news/2025/02/05
https://nplus1.ru/search?tags=876
/material/difficulty/1
https://nplus1.ru/news/2025/02/05/new-painted-etruscan-tomb
/news/2025/02/05
https://nplus1.ru/search?tags=874
/material/difficulty/2
https://nplus1.ru/news/2025/02/05/rhinoderma-darwinii
https://nplus1.ru/material/2024/12/13/nature-2024
/material/2024/12/13
https://nplus1.ru/search?tags=903
/material/difficulty/2
https://nplus1.ru/material/2024/12/13/nature-2024
/news/2025/02/04
https://nplus1.ru/search?tags=880
/material/difficulty/4
https://nplus1.ru/news/2025/02/04/schrodinger-basin
/news/2025/02/04
https://nplus1.ru/search?tags=872
/material/difficulty/1
https://nplus1.ru/news/2025/02/04/wildfires-permafrost
https://nplus1.ru/material/2024/12/13/nothing-to-laugh-at
/material/2024/12/13
https://nplus1.ru/search?tags=885
/material/difficulty/4
https://nplus1.ru/material/2024/12/13/nothing-to-laugh-at
https://nplus1.ru/material/2024/12/05/science-in-asia-2
https://nplus1.ru/search?tags=812
/material/difficulty/2
https://nplus1.ru/material/2024/12/05/science-in-asia-2
/blog/2025/01/24
https://nplus1.ru/search?tags=908
/material/difficulty/2
/author/perst
https://nplus1.ru/blog/2025/01/24/perst-49
/news/2025/02/04
https://nplus1.ru/search?tags=876
/material/difficulty/2
https://nplus1.ru/news/2025/02/04/vampire-grave-found-in-croatia
/news/2025/02/04
https://nplus1.ru/search?tags=883
/material/difficulty/1
https://nplus1.ru/news/2025/02/04/pipistrel-nuuva-v300-first-flight
/news/2025/02/04
https://nplus1.ru/search?tags=882
/material/difficulty/1
https://nplus1.ru/news/2025/02/04/you-are-the-sweetest
https://nplus1.ru/material/2024/12/03/diagnosis-ex-machina
/material/2024/12/03
https://nplus1.ru/search?tags=812
/material/difficulty/4
https://nplus1.ru/material/2024/12/03/diagnosis-ex-machina
/news/2025/02/04
https://nplus1.ru/search?tags=882
/material/difficulty/1
https://nplus1.ru/news/2025/02/04/just-have-a-drink
/news/2025/02/04
https://nplus1.ru/search?tags=873
/material/difficulty/1
https://nplus1.ru/news/2025/02/04/twins-in-the-heart
https://nplus1.ru/material/2024/11/29/crooked-mirrors
/material/2024/11/29
https://nplus1.ru/search?tags=885
/material/difficulty/4
https://nplus1.ru/material/2024/11/29/crooked-mirrors
https://nplus1.ru/material/2024/11/26/%D1%81ities-as-sanctuaries
https://nplus1.ru/search?tags=874
/material/difficulty/3
https://nplus1.ru/material/2024/11/26/%D1%81ities-as-sanctuaries
/blog/2025/01/22
https://nplus1.ru/search?tags=874
/material/difficulty/1
/author/alpina-non-fiksn
https://nplus1.ru/blog/2025/01/22/fuzz
/news/2025/02/04
https://nplus1.ru/search?tags=889
/material/difficulty/4
https://nplus1.ru/news/2025/02/04/stigmatodactylus-sikokianus
/news/2025/02/04
https://nplus1.ru/search?tags=876
/material/difficulty/3
https://nplus1.ru/news/2025/02/04/rune-stone-from-norway
/news/2025/02/03
https://nplus1.ru/search?tags=872
/material/difficulty/1
https://nplus1.ru/news/2025/02/03/cooling-parks
https://nplus1.ru/material/2024/11/25/get-the-oil
/material/2024/11/25
https://nplus1.ru/search?tags=812
/material/difficulty/1
https://nplus1.ru/material/2024/11/25/get-the-oil
https://nplus1.ru/blog/2025/01/28/khlestakov
/blog/2025/01/28
https://nplus1.ru/search?tags=898
/material/difficulty/1
https://nplus1.ru/blog/2025/01/28/khlestakov
https://nplus1.ru/material/2025/01/30/lost-legs
/material/2025/01/30
https://nplus1.ru/search?tags=874
https://nplus1.ru/search?tags=878
/material/difficulty/4
https://nplus1.ru/material/2025/01/30/lost-legs
https://nplus1.ru/news/2025/01/27/cl-goes-through-graphene
https://nplus1.ru/news/2025/01/27/schrodinger-cat-qudit-states
https://nplus1.ru/news/2025/01/28/helical-trilayer-graphene
https://nplus1.ru/news/2025/01/30/quantum-stirling-engine
https://nplus1.ru/material/2025/01/30/lost-legs
https://nplus1.ru/news/2025/01/31/depression-sd2-gwas-mr
https://nplus1.ru/news/2025/02/04/schrodinger-basin
https://nplus1.ru/news/2025/02/06/genetic-origin-of-the-yamnaya-people
https://nplus1.ru/news/2025/02/06/genomic-history-of-north-pontic-region
https://nplus1.ru/news/2025/02/06/mo-as-good-as-ir
https://nplus1.ru/material/2025/02/07/quantum-correction
https://nplus1.ru/news/2025/02/10/elastocaloric-cooling
https://nplus1.ru/material/2025/02/10/vyzov-2024-breakthroughs
https://nplus1.ru/news/2025/02/10/inner-core-boundary-deformation
https://nplus1.ru/news/2025/02/10/tibetan-plateau-tectonic-evolution
https://nplus1.ru/about
https://nplus1.ru/difficult
https://nplus1.ru/adv
https://nplus1.ru/blog/2022/04/01/samotek
/cdn-cgi/l/email-protection#ee8082ae809e829b9ddfc09c9b
/cdn-cgi/l/email-protection#eb82858d84ab859b879e98dac5999e
/personal-data-policy
https://t.me/nplusone
https://vk.com/nplusone
https://ok.ru/nplus1
https://twitter.com/nplusodin

Ссылок много. Но нам нужны только новости — ссылки, которые начинаются со слова `/news`. Добавим условие: будем выбирать только те ссылки, в которых есть `/news`. Кроме того, нам не нужны их внутренние ссылки — поэтому в качестве ещё одного фильтра потребуем, чтобы ссылка начиналась с `https://`.

Создадим пустой список `urls` и будем добавлять в него только ссылки, удовлетворяющие заданным нами условиям:

In [ ]:
urls = []

for link in soup.find_all('a'):
    if '/news' in link.get('href') and link.get('href').startswith('https://'):
        urls.append(link.get('href'))
urls

['https://nplus1.ru/news/2025/02/07/bonobos-theory-of-mind',
 'https://nplus1.ru/news/2025/02/10/tibetan-plateau-tectonic-evolution',
 'https://nplus1.ru/news/2025/02/10/inner-core-boundary-deformation',
 'https://nplus1.ru/news/2025/02/10/real-world-math',
 'https://nplus1.ru/news/2025/02/10/byzantine-ascetic-burial',
 'https://nplus1.ru/news/2025/02/10/cayman-islands-earthquake',
 'https://nplus1.ru/news/2025/02/10/valdegoba-cave',
 'https://nplus1.ru/news/2025/02/10/elastocaloric-cooling',
 'https://nplus1.ru/news/2025/02/10/super-heavy-b15-static-fire-test',
 'https://nplus1.ru/news/2025/02/07/bonobos-theory-of-mind',
 'https://nplus1.ru/news/2025/02/07/magdalenian-cannibalism',
 'https://nplus1.ru/news/2025/02/07/taste-the-tess',
 'https://nplus1.ru/news/2025/02/07/so-sad-but-true',
 'https://nplus1.ru/news/2025/02/07/vegavis-iaai-skull',
 'https://nplus1.ru/news/2025/02/07/temporal-turnover',
 'https://nplus1.ru/news/2025/02/06/cracking-boiled-egg',
 'https://nplus1.ru/news/2025/02/06/mo-as-good-as-ir',
 'https://nplus1.ru/news/2025/02/06/genomic-history-of-north-pontic-region',
 'https://nplus1.ru/news/2025/02/06/pig-kidneys-trial-go',
 'https://nplus1.ru/news/2025/02/06/rats-global-warming',
 'https://nplus1.ru/news/2025/02/06/omicron-escapes',
 'https://nplus1.ru/news/2025/02/06/genetic-origin-of-the-yamnaya-people',
 'https://nplus1.ru/news/2025/02/05/human-crowd-oscillations',
 'https://nplus1.ru/news/2025/02/05/greenland-crevasse-fields',
 'https://nplus1.ru/news/2025/02/05/mobile-not-carcinogenic',
 'https://nplus1.ru/news/2025/02/05/auricular-muscles',
 'https://nplus1.ru/news/2025/02/05/new-painted-etruscan-tomb',
 'https://nplus1.ru/news/2025/02/05/rhinoderma-darwinii',
 'https://nplus1.ru/news/2025/02/04/schrodinger-basin',
 'https://nplus1.ru/news/2025/02/04/wildfires-permafrost',
 'https://nplus1.ru/news/2025/02/04/vampire-grave-found-in-croatia',
 'https://nplus1.ru/news/2025/02/04/pipistrel-nuuva-v300-first-flight',
 'https://nplus1.ru/news/2025/02/04/you-are-the-sweetest',
 'https://nplus1.ru/news/2025/02/04/just-have-a-drink',
 'https://nplus1.ru/news/2025/02/04/twins-in-the-heart',
 'https://nplus1.ru/news/2025/02/04/stigmatodactylus-sikokianus',
 'https://nplus1.ru/news/2025/02/04/rune-stone-from-norway',
 'https://nplus1.ru/news/2025/02/03/cooling-parks',
 'https://nplus1.ru/news/2025/01/27/cl-goes-through-graphene',
 'https://nplus1.ru/news/2025/01/27/schrodinger-cat-qudit-states',
 'https://nplus1.ru/news/2025/01/28/helical-trilayer-graphene',
 'https://nplus1.ru/news/2025/01/30/quantum-stirling-engine',
 'https://nplus1.ru/news/2025/01/31/depression-sd2-gwas-mr',
 'https://nplus1.ru/news/2025/02/04/schrodinger-basin',
 'https://nplus1.ru/news/2025/02/06/genetic-origin-of-the-yamnaya-people',
 'https://nplus1.ru/news/2025/02/06/genomic-history-of-north-pontic-region',
 'https://nplus1.ru/news/2025/02/06/mo-as-good-as-ir',
 'https://nplus1.ru/news/2025/02/10/elastocaloric-cooling',
 'https://nplus1.ru/news/2025/02/10/inner-core-boundary-deformation',
 'https://nplus1.ru/news/2025/02/10/tibetan-plateau-tectonic-evolution']

Теперь наша задача сводится к следующему: изучить одну страницу с новостью; научиться из нее вытаскивать текст и всю необходимую нам информацию; а затем применить весь набор действий к каждой ссылке из `urls` посредством цикла.

Для начала посмотрим на новость с индексом 3 (у вас, конечно, будет другая, чем та, что ниже, — новости обновляются; портал — живой и работающий).

In [ ]:
url0 = urls[3]

page0 = requests.get(url0)
soup0 = BeautifulSoup(page0.text, 'html')
soup0

<!DOCTYPE html>
<html lang="ru" prefix="og: http://ogp.me/ns#">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Школьная математика не помогла индийским детям на рынке. А дети, торгующие на рынках, плохо справлялись с абстрактными заданиями</title>
<link as="font" crossorigin="" href="https://staticn1.nplus1.ru/fonts/AeonikPro/AeonikPro-Regular.woff2" rel="preload" type="font/woff2"/>
<link as="font" crossorigin="" href="https://staticn1.nplus1.ru/fonts/Spectral/Spectral-Regular.woff" rel="preload" type="font/woff2"/>
<link href="/front-build/css/main.css?id=842e64708435127ee441c2e86afffea2" rel="stylesheet"/>
<link href="/front-build/css/app.css?id=92673ebe7185ebc42e29fc7294a4c65f" rel="stylesheet"/>
<link href="/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/site.webmanifest" rel="manifest"/>
<link color="#f26e40" href="/safari-pinned-tab.svg" rel="mask-icon"/>
<meta content="#f26e40" name="msapplication-TileColor"/>
<meta content="#ffffff" name="theme-color"/>
<link href="https://nplus1.ru/news/2025/02/10/real-world-math" rel="canonical"/>
<meta content="8c90b02c84ac3b72" name="yandex-verification"/>
<meta content="b419949322895fc9106e24ed01be58ac" name="pmail-verification"/>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':

    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],

    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=

    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);

    })(window,document,'script','dataLayer','GTM-PJWMQBQ');</script>
<!-- End Google Tag Manager -->
<!-- HuggingCat -->
<script async="" src="https://huggingcat-web.pages.dev/mywidget.js?static=true"></script>
<script>
            (function (c, a) {
                var t = (c[a] = c[a] || []);
                t.push(["init"]);
            })(window, "hc");
        </script>
<!-- End HuggingCat -->
<!-- Ads -->
<script src="/front-build/js/modules/prebid.js?id=ddf9cebd6b4c7a66be2ec26a926d5f3c"></script>
<script src="/front-build/js/modules/initPrebidAds.js?id=1884da35da66817a1cc5dbcb173c1347"></script>
<script src="https://widget.sparrow.ru/js/embed.js"></script>
<!-- End Ads -->
<meta content="N + 1 — главное издание о науке, технике и технологиях" name="description"/>
<meta content="N + 1 — главное издание о науке, технике и технологиях" property="og:site_name"/>
<meta content="Школьная математика не помогла индийским детям на рынке" property="og:title"/>
<meta content="https://minio.nplus1.ru/app-images/992546/67a9934b7a954_cover_share.jpg" property="og:image"/>
<meta content="https://nplus1.ru/news/2025/02/10/real-world-math" property="og:url"/>
<meta content="N + 1 — главное издание о науке, технике и технологиях" property="og:description"/>
<meta content="article" property="og:type"/>
<meta content="2025-02-10" itemprop="datePublished"/>
<!-- amp page -->
<link href="https://nplus1.ru/news/2025/02/10/real-world-math/amp" rel="amphtml"/>
<meta content="2025-02-10" itemprop="datePublished"/>
<meta content="Катерина Петрова" name="mediator_author"/>
<meta content="Катерина Петрова" name="author"/>
<meta content="" name="copyright"/>
<script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "NewsArticle",
      "mainEntityOfPage": {
        "@type": "WebPage",
        "@id": "https://nplus1.ru/news/2025/02/10/real-world-math"
      },
      "headline": "Школьная математика не помогла индийским детям на рынке",
      "description": "А дети, торгующие на рынках, плохо справлялись с абстрактными заданиями",
            "image": "https://minio.nplus1.ru/app-images/992546/67a9934b7a954_cover_share.jpg",




          "author": {
        "@type": "Person",
        "name": "Катерина Петрова",
                "image": "https://staticn1.nplus1.ru/image-new/logo-alt.png",
              "url": "https://nplus1.ru/author/petrova"
        },

        "publisher": {
      "@type": "Organization",
      "name": "N+1",
      "logo": {
        "@type": "ImageObject",
        "url": "https://minio.nplus1.ru/app-images/992546/67a9934b7a954_cover_share.jpg"
      }
    },
    "datePublished": "2025-02-10",
      "dateModified": "2025-02-10"
    }



    </script>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="@nplusodin" name="twitter:site"/>
<meta content="Школьная математика не помогла индийским детям на рынке" name="twitter:title"/>
<meta content="N + 1 — главное издание о науке, технике и технологиях" name="twitter:description"/>
<meta content="https://minio.nplus1.ru/app-images/992546/67a9934b7a954_cover_share.jpg" name="twitter:image"/>
<link href="https://nplus1.ru/rss" rel="alternate" title="RSS" type="application/rss+xml"/>
</head>
<body class="antialiased">
<!-- Top.Mail.Ru counter -->
<script type="text/javascript">

var tmr = window.tmr || (window._tmr = []);

_tmr.push({id: "3377932", type: "pageView", start: (new Date()).getTime()});

(function (d, w, id) {

  if (d.getElementById(id)) return;

  var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true; ts.id = id;

  ts.src = "https://top-fwz1.mail.ru/js/code.js";

  var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};

  if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }

})(document, window, "tmr-code");

</script>
<noscript><div><img alt="Top.Mail.Ru" src="https://top-fwz1.mail.ru/counter?id=3377932;js=na" style="position:absolute;left:-9999px;"/></div></noscript>
<!-- /Top.Mail.Ru counter -->
<!-- Google Tag Manager (noscript) -->
<noscript><iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-PJWMQBQ" style="display:none;visibility:hidden" width="0"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div class="font-aeonik text-main-black flex flex-col min-h-screen pt-15 bg-light-gray" id="appfront">
<header class="bg-light-gray fixed h-15 left-0 top-0 w-full z-50" data-ref-header="" ref="headerRef">
<div class="absolute bg-main-gray/5 bottom-0 left-0 top-0" id="progressBar" style="z-index: -1"></div>
<div class="border-b border-main-gray h-full">
<div class="2xl:max-w-1280 px-6 md:px-8 lg:px-10 xl:px-20 2xl:px-0 mx-auto flex justify-between items-center h-full" data-ref-header-container="" ref="headerContainerRef">
<button aria-label="Go" class="w-7.5 h-7.5" data-ref-header-menu-btn="" id="topMenuBtn" ref="headerMenuBtnRef">
<template v-if="isOpenDesktopMenu || isOpenMobileMenu">
<svg class="w-full h-full">
<use xlink:href="#n1_cross_menu"></use>
</svg>
</template>
<template v-else="">
<svg class="w-full h-full">
<use xlink:href="#n1_burger"></use>
</svg>
</template>
</button>
<div>
<a href="/">
<img alt="as" height="23" loading="lazy" src="https://staticn1.nplus1.ru/image-new/logo.svg" width="57"/>
</a>
</div>
<a class="w-7.5 h-7.5" href="/search">
<svg class="w-full h-full">
<use xlink:href="#n1_pupa"></use>
</svg>
</a>
</div>
</div>
<nav :style="stylesNavDesktop" class="relative bg-light-gray max-h-0 n1_top_nav overflow-hidden" id="navMenu" v-if="isOpenDesktopMenu">
<div class="2xl:max-w-1280 px-6 md:px-8 lg:px-10 xl:px-20 2xl:px-0 mx-auto h-full flex flex-col overflow-y-auto">
<div class="py-12 mb-12 border-b border-gray-2 text-18 grid grid-cols-flow lg:grid-cols-12 gap-x-5 md:gap-x-9">
<!--
        <a @click.native="menuClose"
           class="col-span-3 flex gap-x-2 lg:gap-x-5 items-center hover:text-main transition-colors duration-75"
           href="/lk">
          <svg class="h-10 lg:h-12 w-10 lg:w-12 shrink-0">
            <use xlink:href="#n1_person"></use>
          </svg>
          <span>Личный кабинет</span>
        </a>
        -->
<a class="col-span-3 lg:col-span-2 col-start-7 lg:col-start-9 flex items-center hover:text-main transition-colors duration-75" href="https://offline.nplus1.ru/">N + offline</a>
<a class="col-span-3 lg:col-span-2 col-start-10 lg:col-start-11 flex items-center hover:text-main transition-colors duration-75" href="https://nplus.pro/">N + production</a>
</div>
<div class="grid grid-cols-12 gap-x-5 gap-y-5 md:gap-y-9 pb-6">
<div class="col-span-6 md:col-span-3 text-20 lg:text-26 xl:text-34 font-spectral flex flex-col gap-y-3">
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/about">
                О нас
              </a>
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/difficult" target="_blank">
                Сложность
              </a>
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/adv" target="_blank">
                Рекламодателям
              </a>
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/blog/2022/04/01/samotek" target="_blank">
                Авторам
              </a>
</div>
<div class="col-span-6 md:col-span-3 text-18 lg:text-24 xl:text-32 text-main flex flex-col gap-y-3">
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=946">Игры</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=869">Физика</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=874">Зоология</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=880">Астрономия</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=768">Генетика</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=890">Математика</a>
</div>
<div class="col-span-6 md:col-span-3 text-18 lg:text-24 xl:text-32 text-main flex flex-col gap-y-3">
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=871">Космонавтика</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=876">Археология</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=775">Нейронауки</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=767">На мышах</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=771">Звук</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=772">Красота</a>
</div>
<div class="col-span-6 md:col-span-3 text-18 lg:text-24 xl:text-32 text-main flex flex-col gap-y-3">
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=778">Научные закрытия</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=917">ИИ спешит на помощь</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=918">Когда рассеется дым</a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=824">Книжная полка</a>
</div>
</div>
<div class="py-12 mt-auto border-t border-gray-2 text-18 grid grid-cols-12 gap-x-5 md:gap-x-9">
<ul class="flex gap-2.5">
<li>
<a class="hover:text-main" href="https://t.me/nplusone" target="_blank">
<svg class="w-12 h-12">
<use xlink:href="#n1_tg"></use>
</svg>
</a>
</li>
<li>
<a class="hover:text-main" href="https://vk.com/nplusone" target="_blank">
<svg class="w-12 h-12">
<use xlink:href="#n1_vk"></use>
</svg>
</a>
</li>
<li>
<a class="hover:text-main" href="https://ok.ru/nplus1" target="_blank">
<svg class="w-12 h-12">
<use xlink:href="#n1_ok"></use>
</svg>
</a>
</li>
<li class="w-12">
<a class="hover:text-main" href="https://twitter.com/nplusodin" target="_blank">
<svg class="w-12 h-12">
<use xlink:href="#n1_tw"></use>
</svg>
</a>
</li>
</ul>
</div>
</div>
</nav>
<nav :style="stylesNavMobile" class="relative bg-white max-h-0 n1_top_nav overflow-hidden" id="mobNavMenu" v-if="isOpenMobileMenu">
<div class="2xl:max-w-1280 px-6 md:px-8 lg:px-10 xl:px-20 2xl:px-0 mx-auto h-full flex flex-col overflow-y-auto">
<div class="text-30 font-spectral flex flex-col gap-y-5 mb-10 mt-10">
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/about">
                О нас
              </a>
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/difficult" target="_blank">
                Сложность
              </a>
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/adv" target="_blank">
                Рекламодателям
              </a>
<a class="hover:text-main transition-colors duration-75" href="https://nplus1.ru/blog/2022/04/01/samotek" target="_blank">
                Авторам
              </a>
</div>
<div class="text-28 text-main flex flex-col gap-y-2.5 mb-10">
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=946">Игры
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=869">Физика
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=874">Зоология
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=880">Астрономия
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=768">Генетика
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=890">Математика
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=871">Космонавтика
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=876">Археология
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=775">Нейронауки
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=767">На мышах
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=771">Звук
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=772">Красота
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=778">Научные закрытия
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=917">ИИ спешит на помощь
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=918">Когда рассеется дым
          </a>
<a class="hover:underline transition-colors duration-75" href="https://nplus1.ru/search?tags=824">Книжная полка
          </a>
</div>
<div class="max-w-full flex py-5 border-t border-gray-2">
<div class="flex gap-x-5 overflow-x-auto">
<a class="hover:text-main whitespace-nowrap" href="https://offline.nplus1.ru/">N + offline</a>
<a class="hover:text-main whitespace-nowrap" href="https://nplus.pro/">N + production</a>
</div>
</div>
<div class="pt-5 pb-10 border-t border-gray-2 text-18">
<ul class="flex gap-2.5">
<li>
<a class="hover:text-main" href="https://t.me/nplusone" target="_blank">
<svg class="w-10 h-10">
<use xlink:href="#n1_tg"></use>
</svg>
</a>
</li>
<li>
<a class="hover:text-main" href="https://vk.com/nplusone" target="_blank">
<svg class="w-10 h-10">
<use xlink:href="#n1_vk"></use>
</svg>
</a>
</li>
<li>
<a class="hover:text-main" href="https://ok.ru/nplus1" target="_blank">
<svg class="w-10 h-10">
<use xlink:href="#n1_ok"></use>
</svg>
</a>
</li>
<li class="w-12">
<a class="hover:text-main" href="https://twitter.com/nplusodin" target="_blank">
<svg class="w-10 h-10">
<use xlink:href="#n1_tw"></use>
</svg>
</a>
</li>
</ul>
</div>
</div>
</nav>
</header>
<app-heading-nav></app-heading-nav>
<section class="mb-15 md:mb-20">
<div class="2xl:max-w-1280 px-6 md:px-8 lg:px-10 xl:px-20 2xl:px-0 mx-auto grid grid-cols-6 md:grid-cols-12 gap-x-5 md:gap-x-7.5 relative" data-heading-wrap="">
<!--tags-->
<div class="relative flex-wrap col-span-6 md:col-span-12 lg:col-span-2 lg:row-span-3 mt-5 -mb-2.5 lg:-mb-0 lg:mt-10 content-start mr-9">
<div class="flex flex-wrap lg:mb-10 gap-2 text-tags xl:pr-9">
<span class="relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 group pl-2 flex inline-flex items-center">
<span class="group-hover:text-main transition-colors duration-75">17:48</span>
</span>
<a class="relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 group pl-2 flex inline-flex items-center" href="/news/2025/02/10">
<span class="group-hover:text-main transition-colors duration-75">10.02.25</span>
</a>
<a class="relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 group pl-2 flex inline-flex items-center" href="/material/difficulty/2">
<svg class="w-4 h-4 mr-1 group-hover:text-main transition-colors duration-75 stroke-current">
<use xlink:href="#n1_star"></use>
</svg>
<span class="group-hover:text-main transition-colors duration-75">2.5</span>
</a>
<a class="relative before:block before:w-px before:bg-current before:h-4 before:absolute before:left-0 group pl-2 flex inline-flex items-center" href="https://nplus1.ru/search?tags=882">
<span class="group-hover:text-main transition-colors duration-75">Психология</span>
</a>
</div>
<div class="hidden lg:flex items-center gap-x-2">
<a class="group" href="https://nplus1.ru/material-print/70494" target="_blank">
<svg class="group-hover:text-main transition-colors duration-75 stroke-current" fill="none" height="30" viewbox="0 0 22 30" width="22" xmlns="http://www.w3.org/2000/svg">
<rect height="29" width="21" x="0.5" y="0.5"></rect>
<line x1="4" x2="18" y1="7.5" y2="7.5"></line>
<line x1="4" x2="18" y1="21.5" y2="21.5"></line>
<line x1="4" x2="18" y1="14.5" y2="14.5"></line>
</svg>
</a>
<app-copy-material link="https://nplus1.ru/news/2025/02/10/real-world-math" type="full-2"></app-copy-material>
</div>
<div class="w-full flex flex-col mt-5">
</div>
<div class="header-bidding-ad-container header-bidding-ad-container--left hidden lg:hidden flex-col mt-5 w-160 h-600">
<app-header-bidding-ad :close-button="false" :id="898517" height="600px" width="160px"></app-header-bidding-ad>
</div>
</div>
<!--dotes menu mobile-->
<template v-if="isMobile">
<button class="absolute flex right-5 top-5 z-30 text-main-black">
<svg class="fill-current" fill="none" height="30" viewbox="0 0 30 30" width="30" xmlns="http://www.w3.org/2000/svg">
<path clip-rule="evenodd" d="M17 6C17 6.55228 16.5523 7 16 7H15C14.4477 7 14 6.55228 14 6V5C14 4.44772 14.4477 4 15 4H16C16.5523 4 17 4.44772 17 5V6ZM17 23C17 23.5523 16.5523 24 16 24H15C14.4477 24 14 23.5523 14 23V22C14 21.4477 14.4477 21 15 21H16C16.5523 21 17 21.4477 17 22V23ZM14 14.5C14 15.0523 14.4477 15.5 15 15.5H16C16.5523 15.5 17 15.0523 17 14.5V13.5C17 12.9477 16.5523 12.5 16 12.5H15C14.4477 12.5 14 12.9477 14 13.5V14.5Z" fill-rule="evenodd"></path>
</svg>
</button>
<div :class="{
           'transition-transform flex items-center gap-x-7.5 absolute top-0 right-0 w-full px-6 md:px-8 h-20 bg-white z-30 justify-end bg-light-gray':true,
           '-translate-x-full': !isOpenMobileDotsMenu,
           '-translate-x-0': isOpenMobileDotsMenu
           }" ref="mobileDotsMenuRef">
<app-copy-material link="https://nplus1.ru/news/2025/02/10/real-world-math" type="mobile"></app-copy-material>
<button aria-label="Go" class="group">
<svg class="group-focus:text-main transition-colors duration-75 stroke-current" fill="none" height="40" viewbox="0 0 30 40" width="30" xmlns="http://www.w3.org/2000/svg">

В коде каждой страницы с новостью есть часть с мета-информацией: датой, именем автора и прочим. Такая информация окружена тэгом `<meta></meta>`. Кажется, это как раз то, что надо! Посмотрим детельнее:

In [ ]:
soup0.find_all('meta')

[<meta charset="utf-8"/>,
 <meta content="width=device-width, initial-scale=1" name="viewport"/>,
 <meta content="#f26e40" name="msapplication-TileColor"/>,
 <meta content="#ffffff" name="theme-color"/>,
 <meta content="8c90b02c84ac3b72" name="yandex-verification"/>,
 <meta content="b419949322895fc9106e24ed01be58ac" name="pmail-verification"/>,
 <meta content="N + 1 — главное издание о науке, технике и технологиях" name="description"/>,
 <meta content="N + 1 — главное издание о науке, технике и технологиях" property="og:site_name"/>,
 <meta content="Школьная математика не помогла индийским детям на рынке" property="og:title"/>,
 <meta content="https://minio.nplus1.ru/app-images/992546/67a9934b7a954_cover_share.jpg" property="og:image"/>,
 <meta content="https://nplus1.ru/news/2025/02/10/real-world-math" property="og:url"/>,
 <meta content="N + 1 — главное издание о науке, технике и технологиях" property="og:description"/>,
 <meta content="article" property="og:type"/>,
 <meta content="2025-02-10" itemprop="datePublished"/>,
 <meta content="2025-02-10" itemprop="datePublished"/>,
 <meta content="Катерина Петрова" name="mediator_author"/>,
 <meta content="Катерина Петрова" name="author"/>,
 <meta content="" name="copyright"/>,
 <meta content="summary_large_image" name="twitter:card"/>,
 <meta content="@nplusodin" name="twitter:site"/>,
 <meta content="Школьная математика не помогла индийским детям на рынке" name="twitter:title"/>,
 <meta content="N + 1 — главное издание о науке, технике и технологиях" name="twitter:description"/>,
 <meta content="https://minio.nplus1.ru/app-images/992546/67a9934b7a954_cover_share.jpg" name="twitter:image"/>]

Из этого списка нам нужны части с именем автора, датой и заголовком. Воспользуемся поиском по атрибуту `name`. Передадим функции `find_all()` в качестве аргумента словарь с названием и значением атрибута:

In [ ]:
soup0.find_all('meta', {'name' : 'author'}) # например, автор

Теперь выберем единственный элемент полученного списка (с индексом 0):

In [ ]:
soup0.find_all('meta', {'name' : 'author'})[0]

Нам нужно вытащить из этого объекта `content` — имя автора. Посмотрим на атрибуты:

In [ ]:
soup0.find_all('meta', {'name' : 'author'})[0].attrs

{'name': 'author', 'content': 'Катерина Петрова'}

Как получить отсюда `content`? Очень просто, ведь это словарь! А доставать из словаря значение по ключу мы умеем.

In [ ]:
author = soup0.find_all('meta', {'name' : 'author'})[0].get('content')
author

'Катерина Петрова'

Аналогичным образом извлечем дату и заголовок.

In [ ]:
date = soup0.find_all('meta', {'itemprop' : 'datePublished'})[0].get('content')
title = soup0.find_all('meta', {'property' : 'og:title'})[0].get('content')

In [ ]:
title

'Школьная математика не\xa0помогла индийским детям на\xa0рынке'

Что за `\ха0`, кстати — есть идеи? :)

Теперь осталось совсем чуть-чуть. Написать готовую функцию для всех проделанных нами действий и применить ее в цикле ко всем ссылкам в списке `urls`. Напишем! Аргументом функции будет ссылка на новость, а возвращать она будет название новости и всю необходимую информацию про неё (дата, автор и т.п.). Скопируем для этого соответствующие строки кода выше.

In [ ]:
def GetNews(url0):
    """
    Возвращает кортеж с url0, date, author, title.
    Параметры:

    url0 - ссылка на новость (строка).
    """
    page0 = requests.get(url0)
    soup0 = BeautifulSoup(page0.text, 'html')

    try:
        author = soup0.find_all('meta', {'name' : 'author'})[0].get('content')
    except IndexError:
        author = None
    date = soup0.find_all('meta', {'itemprop' : 'datePublished'})[0].get('content')
    title = soup0.find_all('meta', {'property' : 'og:title'})[0].get('content')

    return url0, date, author, title

Уфф. Осталось применить нашу функцию в цикле. Но давайте не будем спешить: импортируем функцию `sleep` для задержки, чтобы на каждой итерации цикла, прежде чем перейти к следующей новости, Python ждал несколько секунд. Во-первых, это нужно, чтобы сайт «не понял», чтобы мы его грабим, да еще и автоматически. Во-вторых, с небольшой задержкой всегда есть гарантия, что страница прогрузится (сейчас это не очень важно, но особенно актуально будет, если рассматривать встраивание в браузер с Selenium). Приступим.

In [ ]:
from time import sleep

In [ ]:
len(urls)

50

In [ ]:
news = [] # это будет список из кортежей, в которых будут храниться данные по каждой новости

for link in urls[10:25]:
    print(link)
    res = GetNews(link)
    news.append(res)

    sleep(3) # задержка в 3 секунды

https://nplus1.ru/news/2025/02/07/magdalenian-cannibalism
https://nplus1.ru/news/2025/02/07/taste-the-tess
https://nplus1.ru/news/2025/02/07/so-sad-but-true
https://nplus1.ru/news/2025/02/07/vegavis-iaai-skull
https://nplus1.ru/news/2025/02/07/temporal-turnover
https://nplus1.ru/news/2025/02/06/cracking-boiled-egg
https://nplus1.ru/news/2025/02/06/mo-as-good-as-ir
https://nplus1.ru/news/2025/02/06/genomic-history-of-north-pontic-region
https://nplus1.ru/news/2025/02/06/pig-kidneys-trial-go
https://nplus1.ru/news/2025/02/06/rats-global-warming
https://nplus1.ru/news/2025/02/06/omicron-escapes
https://nplus1.ru/news/2025/02/06/genetic-origin-of-the-yamnaya-people
https://nplus1.ru/news/2025/02/05/human-crowd-oscillations
https://nplus1.ru/news/2025/02/05/greenland-crevasse-fields
https://nplus1.ru/news/2025/02/05/mobile-not-carcinogenic

Так теперь выглядит первый элемент списка:

In [ ]:
news[0]

('https://nplus1.ru/news/2025/02/07/magdalenian-cannibalism',
 '2025-02-07',
 'Михаил Подрезов',
 'На\xa0костях древних охотников-собирателей из\xa0Машицкой пещеры выявили следы каннибализма')

Импортируем `pandas` и создадим датафрейм из списка кортежей:

In [ ]:
import pandas as pd

df = pd.DataFrame(news)
df.head(2)

,0,1,2,3
0,https://nplus1.ru/news/2025/02/07/magdalenian-...,2025-02-07,Михаил Подрезов,На костях древних охотников-собирателей из Маш...
1,https://nplus1.ru/news/2025/02/07/taste-the-tess,2025-02-07,Олег Лищук,Чрескожная электростимуляция помогла при гастр...

Как видите, это произошло довольно легко.

Переименуем столбцы в базе.

In [ ]:
df.columns = ['link', 'date', 'author', 'title']

In [ ]:
df

,link,date,author,title
0,https://nplus1.ru/news/2025/02/07/magdalenian-...,2025-02-07,Михаил Подрезов,На костях древних охотников-собирателей из Маш...
1,https://nplus1.ru/news/2025/02/07/taste-the-tess,2025-02-07,Олег Лищук,Чрескожная электростимуляция помогла при гастр...
2,https://nplus1.ru/news/2025/02/07/so-sad-but-true,2025-02-07,Олег Лищук,Эффективное лечение психических расстройств по...
3,https://nplus1.ru/news/2025/02/07/vegavis-iaai...,2025-02-07,Сергей Коленов,Череп выдал в позднемеловой птице из Антарктид...
4,https://nplus1.ru/news/2025/02/07/temporal-tur...,2025-02-07,Марина Попова,Резкие потепления и похолодания подорвали усто...
5,https://nplus1.ru/news/2025/02/06/cracking-boi...,2025-02-06,Егор Конюхов,Физики научились оптимально варить яйца
6,https://nplus1.ru/news/2025/02/06/mo-as-good-a...,2025-02-06,Михаил Бойм,Молибденовые комплексы не уступили иридиевым в...
7,https://nplus1.ru/news/2025/02/06/genomic-hist...,2025-02-06,Михаил Подрезов,Генетики выявили миграции эпохи энеолита в Сев...
8,https://nplus1.ru/news/2025/02/06/pig-kidneys-...,2025-02-06,Олег Лищук,В США разрешили клинические испытания генно-мо...
9,https://nplus1.ru/news/2025/02/06/rats-global-...,2025-02-06,Сергей Коленов,Городские популяции крыс выросли благодаря пот...
10,https://nplus1.ru/news/2025/02/06/omicron-escapes,2025-02-06,Олег Лищук,Эффективность и длительность иммунитета после ...
11,https://nplus1.ru/news/2025/02/06/genetic-orig...,2025-02-06,Михаил Подрезов,Генетики уточнили происхождение ямников
12,https://nplus1.ru/news/2025/02/05/human-crowd-...,2025-02-05,Егор Конюхов,Физики описали поведение многотысячной толпы
13,https://nplus1.ru/news/2025/02/05/greenland-cr...,2025-02-05,Марина Попова,Трещины гренландских льдов по объему догнали П...
14,https://nplus1.ru/news/2025/02/05/mobile-not-c...,2025-02-05,Олег Лищук,Крупный обзор подтвердил неканцерогенность моб...

Всё! Сохраняем датафрейм в файл. Для разнообразия сохраним в Excel:

In [ ]:
df.to_excel('nplus-news.xlsx', index=False)

Дело сделано! Мы молодцы! :)

## Практика

В качестве ещё одного практического примера, на котором можно потренироваться, а заодно и отточить свои навыки парсинга данных, рассмотрим обработку сайта с большим каталогом книг на продажу [(ссылка)](http://books.toscrape.com/catalogue/page-1.html). Сайт этот, кстати, представляет собой специальный тренировочный портал для практики веб-скрейпинга на данных близких к реальным, а значит особых затруднений в процессе его обработки у нас возникнуть не должно.

Сам процесс веб-скрейпинга и парсинга давайте будем осуществлять с минимумом комментариев и пояснений, поскольку глобально мы лишь повторяем то, что уже проделали чуть ранее, — последуем тут старинному принципу: "Нет времени обсуждать — пишем код!" :)

Итак, поехали!

In [ ]:
url = 'http://books.toscrape.com/catalogue/page-1.html'
response = requests.get(url)
response

In [ ]:
response.content[:1000]

b'\n\n<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->\n    <head>\n        <title>\n    All products | Books to Scrape - Sandbox\n</title>\n\n        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />\n        <meta name="created" content="24th Jun 2016 09:30" />\n        <meta name="description" content="" />\n        <meta name="viewport" content="width=device-width" />\n        <meta name="robots" content="NOARCHIVE,NOCACHE" />\n\n        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n        <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n\n        \n            <link rel="shortcut icon" href="../static/oscar/fav'

In [ ]:
tree = BeautifulSoup(response.content, 'html.parser')

In [ ]:
tree.html.head.title.text.strip()

'All products | Books to Scrape - Sandbox'

In [ ]:
books = tree.find_all('article', {'class' : 'product_pod'})
books[5]

<article class="product_pod">
<div class="image_container">
<a href="the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
<div class="product_price">
<p class="price_color">£22.65</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [ ]:
books[5].find('p', {'class': 'price_color'}).text

'£22.65'

In [ ]:
books[5].a.get('href')

'the-requiem-red_995/index.html'

In [ ]:
books[5].h3.a.get('title')

'The Requiem Red'

In [ ]:
books[5].p.get('class')[1]

'One'

In [ ]:
def get_page(p):
    url = f'http://books.toscrape.com/catalogue/page-{p}.html'
    response = requests.get(url)
    tree = BeautifulSoup(response.content, 'html.parser')
    books = tree.find_all('article', {'class' : 'product_pod'})

    info = []

    for book in books:
        info.append({'price': book.find('p', {'class': 'price_color'}).text,
                     'href': book.h3.a.get('href'),
                     'title': book.h3.a.get('title'),
                    'rating': book.p.get('class')[1]})

    return info

In [ ]:
from tqdm import tqdm

In [ ]:
infa = []

for p in tqdm(range(1,51)):
    try:
        infa.extend(get_page(p))
        sleep(5)
    except:
        print(p)

100%|██████████| 50/50 [04:12<00:00,  5.06s/it]

In [ ]:
df = pd.DataFrame(infa)
print(df.shape)
df.head()

(1000, 4)

,price,href,title,rating
0,£51.77,a-light-in-the-attic_1000/index.html,A Light in the Attic,Three
1,£53.74,tipping-the-velvet_999/index.html,Tipping the Velvet,One
2,£50.10,soumission_998/index.html,Soumission,One
3,£47.82,sharp-objects_997/index.html,Sharp Objects,Four
4,£54.23,sapiens-a-brief-history-of-humankind_996/index...,Sapiens: A Brief History of Humankind,Five

In [ ]:
df.to_csv('books_parsed.csv', index=False)

In [ ]:
df.to_excel('books_parsed.xlsx', index=False)

Ну что, всё получилось, всё понятно?

Попробуйте теперь самостоятельно!

### Задания для самостоятельного решения (парсинг сайта)

По аналогии с примером выше вам предстоит собрать данные с сайта https://quotes.toscrape.com/.

1) Распарсив html-страницу с цитатами, извлеките с сайта саму цитату, автора цитаты, а также все теги, связанные с этой цитатой.

2) Напишите программу, где пользователь вводит тег, а ему выводятся все цитаты, у которых есть такой тег (например, `'truth'`).

In [ ]:
# your code here